# Generated by Django 2.0.4 on 2018-06-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('coin', 'date')},
        ),
    ]
