# Generated by Django 2.0.4 on 2018-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180616_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='marketcap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
