# Generated by Django 2.0.4 on 2018-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='high_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='low_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
