# Generated by Django 2.0.4 on 2018-06-30 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180630_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('volume', models.CharField(max_length=100)),
                ('marketcap', models.CharField(max_length=100)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cryptocurrency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('coin', 'date')},
        ),
    ]
